<?php

namespace Ceten\CetenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * Update products stocks for a given order
     * 
     * @param  ShopOrder $order         
     * @param  boolean   $deleteOrder   Whether the order is deleted or not
     */
    public function updateStock(ShopOrder $order, $orderDeleted=false)
    {
        foreach ($order->getOrders() as $o) {
            $product = $o->getProduct();

            $stock = $product->getStock();
            if ($orderDeleted) {
                $stock += $o->getCount();
            } else {
                $stock -= $o->getCount();
            }
            $product->setStock($stock);
        }

        $this->_em->flush();
    }
}
