security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN_USER_USER_READ:
            - ROLE_ADMIN_USER_USER_LIST
            - ROLE_ADMIN_USER_USER_VIEW

        ROLE_ADMIN_USER_USER_EDIT:
            - ROLE_ADMIN_USER_USER_CREATE
            - ROLE_ADMIN_USER_USER_EDIT
            - ROLE_ADMIN_USER_USER_DELETE
            - ROLE_ADMIN_USER_USER_EXPORT

        ROLE_ADMIN_SHOP_PRODUCT:
            - ROLE_ADMIN_SHOP_PRODUCT_LIST
            - ROLE_ADMIN_SHOP_PRODUCT_VIEW
            - ROLE_ADMIN_SHOP_PRODUCT_CREATE
            - ROLE_ADMIN_SHOP_PRODUCT_EDIT
            - ROLE_ADMIN_SHOP_PRODUCT_DELETE
            - ROLE_ADMIN_SHOP_PRODUCT_EXPORT

        ROLE_ADMIN_SHOP_TAG:
            - ROLE_ADMIN_SHOP_TAG_LIST
            - ROLE_ADMIN_SHOP_TAG_VIEW
            - ROLE_ADMIN_SHOP_TAG_CREATE
            - ROLE_ADMIN_SHOP_TAG_EDIT
            - ROLE_ADMIN_SHOP_TAG_DELETE
            - ROLE_ADMIN_SHOP_TAG_EXPORT

        # Enable admin access
        ROLE_ADMIN:         [ROLE_USER, ROLE_SONATA_ADMIN]

        # Shop admin
        ROLE_ADMIN_SHOP:    [ROLE_ADMIN, ROLE_ADMIN_SHOP_PRODUCT, ROLE_ADMIN_SHOP_TAG]

        # User admins
        ROLE_READ_USER:     [ROLE_ADMIN, ROLE_ADMIN_USER_USER_READ]
        ROLE_ADMIN_USER:    [ROLE_READ_USER, ROLE_ADMIN_USER_USER_EDIT]

        # BDE

        # Super admin
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN_SHOP]