shop_product:
    resource: "@ShopProductBundle/Controller/"
    type:     annotation
    prefix:   /

shop_shop:
    resource: "@ShopShopBundle/Controller/"
    type:     annotation
    prefix:   /

